// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWsbjb9yumOSWDscRmtPPyeAVpJOQaEb8',
    appId: '1:834517041565:web:7b3c4561a8cf745d176f74',
    messagingSenderId: '834517041565',
    projectId: 'profile-cv-f5637',
    authDomain: 'profile-cv-f5637.firebaseapp.com',
    storageBucket: 'profile-cv-f5637.appspot.com',
    measurementId: 'G-L6JS1CW22T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUK2baJz8gahcz0cmux9_jlrw8ja3DS8U',
    appId: '1:834517041565:android:955aa378510a95eb176f74',
    messagingSenderId: '834517041565',
    projectId: 'profile-cv-f5637',
    storageBucket: 'profile-cv-f5637.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbeEbm23Tlzjy6MDRy22-gwn6WzPtyyxo',
    appId: '1:834517041565:ios:e1ed4ca4dbbe2f54176f74',
    messagingSenderId: '834517041565',
    projectId: 'profile-cv-f5637',
    storageBucket: 'profile-cv-f5637.appspot.com',
    iosBundleId: 'com.example.fproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbeEbm23Tlzjy6MDRy22-gwn6WzPtyyxo',
    appId: '1:834517041565:ios:e1ed4ca4dbbe2f54176f74',
    messagingSenderId: '834517041565',
    projectId: 'profile-cv-f5637',
    storageBucket: 'profile-cv-f5637.appspot.com',
    iosBundleId: 'com.example.fproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWsbjb9yumOSWDscRmtPPyeAVpJOQaEb8',
    appId: '1:834517041565:web:9ec774475769ecf3176f74',
    messagingSenderId: '834517041565',
    projectId: 'profile-cv-f5637',
    authDomain: 'profile-cv-f5637.firebaseapp.com',
    storageBucket: 'profile-cv-f5637.appspot.com',
    measurementId: 'G-5R14LZ8125',
  );
}
